# Generated by Django 3.0.3 on 2020-03-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200224_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='course',
            new_name='module',
        ),
    ]
