# Generated by Django 3.0.3 on 2020-03-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200309_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(null=True, upload_to='course_pictures'),
        ),
    ]
