# Generated by Django 3.0.3 on 2020-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='picture',
            field=models.ImageField(null=True, upload_to='course_pictures/module_pictures/lesson_pictures'),
        ),
        migrations.AddField(
            model_name='module',
            name='picture',
            field=models.ImageField(null=True, upload_to='course_pictures/module_pictures'),
        ),
    ]
