# Generated by Django 3.0.3 on 2020-03-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20200324_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='picture',
            new_name='image',
        ),
    ]
