# Generated by Django 3.0.3 on 2020-03-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0009_auto_20200329_2335'),
        ('course', '0009_auto_20200329_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='educator.Educator'),
        ),
        migrations.AddField(
            model_name='module',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='educator.Educator'),
        ),
    ]
