# Generated by Django 3.0.3 on 2020-02-24 21:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_auto_20200224_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FSTC', 'FROM_STUDENT_TO_COURSE'), ('FSTE', 'FROM_STUDENT_TO_EDUCATOR'), ('FPTE', 'FROM_PARENT_TO_EDUCATOR'), ('FETS', 'FROM_EDUCATOR_TO_STUDENT'), ('FCTS', 'FROM_COURSE_TO_STUDENT')], max_length=4)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('related_course', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='course.Course')),
            ],
        ),
    ]
