# Generated by Django 3.0.3 on 2020-02-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('achievement', '0003_achievement_related_parent'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='related_student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='student.Student'),
        ),
    ]
