# Generated by Django 3.0.3 on 2020-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_auto_20200329_2337'),
        ('course', '0010_auto_20200330_1044'),
        ('student', '0007_auto_20200329_2336'),
        ('educator', '0010_auto_20200330_1044'),
        ('achievement', '0004_achievement_related_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='related_course',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='related_educator',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='related_parent',
        ),
        migrations.RemoveField(
            model_name='achievement',
            name='related_student',
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='course.Course'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_educators',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='educator.Educator'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_parents',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='parent.Parent'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='related_students',
            field=models.ManyToManyField(blank=True, related_name='achievements', to='student.Student'),
        ),
    ]
