# Generated by Django 3.0.3 on 2020-03-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_email'),
        ('achievement', '0006_achievement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_achievements', to='accounts.UserProfile'),
        ),
    ]
