# Generated by Django 3.0.3 on 2020-03-31 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0007_achievement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('From Student to Course', 'From Student To Course'), ('From Student to Educator', 'From Student To Educator'), ('From Parent to Educator', 'From Parent To Educator'), ('From Educator to Student', 'From Educator To Student'), ('From Course to Student', 'From Course To Student')], max_length=36),
        ),
    ]
