# Generated by Django 3.0.3 on 2020-03-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0008_auto_20200331_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='type',
            field=models.CharField(choices=[('FSTC', 'From Student To Course'), ('FSTE', 'From Student To Educator'), ('FPTE', 'From Parent To Educator'), ('FETS', 'From Educator To Student'), ('FCTS', 'From Course To Student')], max_length=4),
        ),
    ]
