# Generated by Django 3.0.3 on 2020-03-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parent_children'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='id',
        ),
    ]
