# Generated by Django 3.0.3 on 2020-02-24 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('course', '0003_auto_20200224_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='educator', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('active', models.BooleanField(default=True)),
                ('contributing_to_courses', models.ManyToManyField(related_name='contributors', to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EducatorSettings',
            fields=[
                ('educator_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to='educator.Educator')),
                ('show_in_listings', models.BooleanField(default=True)),
                ('local_connect', models.BooleanField(default=True)),
            ],
        ),
    ]
