# Generated by Django 3.0.3 on 2020-02-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0004_auto_20200224_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educator',
            old_name='user',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='educatorsettings',
            old_name='educator_profile',
            new_name='id',
        ),
    ]
