# Generated by Django 3.0.3 on 2020-03-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0006_auto_20200323_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='local_connect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='online_connect',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='educator',
            name='show_in_listings',
            field=models.BooleanField(default=True),
        ),
    ]
