# Generated by Django 3.0.3 on 2020-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200329_1622'),
        ('educator', '0007_auto_20200323_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='educator',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='student.Student'),
        ),
    ]
