# Generated by Django 3.0.3 on 2020-03-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0008_educator_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educator',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='contributing_to_courses',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='students',
        ),
    ]
