# Generated by Django 3.0.3 on 2020-03-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200324_2023'),
        ('educator', '0009_auto_20200329_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='educator', serialize=False, to='accounts.UserProfile'),
        ),
    ]
