# Generated by Django 3.0.3 on 2020-02-24 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='id',
        ),
    ]
