# Generated by Django 3.0.3 on 2020-03-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educator', '0009_auto_20200329_2335'),
        ('student', '0005_studentcourse_studentlesson_studentmodule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='educators',
            field=models.ManyToManyField(related_name='students', to='educator.Educator'),
        ),
    ]
