# Generated by Django 3.0.3 on 2020-03-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200324_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='marek@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
