// Website
export const GET_CONTENT = "GET_CONTENT";
export const GET_IDS = "GET_IDS";
export const CHANGE_PAGE = "CHANGE_PAGE";
export const CHANGE_VIEW = "CHANGE_VIEW";
export const CHANGE_SUB_VIEW = "CHANGE_SUB_VIEW";

// Auth
export const USER_LOADED = "USER_LOADED";
export const USER_LOADING = "USER_LOADING";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

// Common
export const GET_PROFILE = "GET_PROFILE";
export const GET_FORM_CONTEXT = "GET_FORM_CONTEXT";
export const GET_DETAILS = "GET_DETAILS";
export const RESET_DETAILS = "RESET_DETAILS";
export const GET_LIST_ITEMS = "GET_LIST_ITEMS";
export const RESET_LIST_ITEMS = "RESET_LIST_ITEMS";
export const CREATE_ITEM = "CREATE_ITEM";
export const COMMON_LOADING_FORM = "COMMON_LOADING_FORM";
export const COMMON_LOADED_FORM = "COMMON_LOADED_FORM";
export const COMMON_LOADING_DETAILS = "COMMON_LOADING_DETAILS";
export const COMMON_LOADED_DETAILS = "COMMON_LOADED_DETAILS";
export const COMMON_LOADING_LIST_ITEMS = "COMMON_LOADING_LIST_ITEMS";
export const COMMON_LOADED_LIST_ITEMS = "COMMON_LOADED_LIST_ITEMS";
export const COMMON_LOADING_PROFILE = "COMMON_LOADING_PROFILE";
export const COMMON_LOADED_PROFILE = "COMMON_LOADED_PROFILE";
export const RESET_MY_PROFILE = "RESET_MY_PROFILE";
export const RESET_PROFILE = "RESET_PROFILE";
export const RESET_FORM_CONTEXT = "RESET_FORM_CONTEXT";

// Profile
export const PICTURE_UPLOADED = "PICTURE_UPLOADED";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

// Message alerts
export const RETURN_ERRORS = "RETURN_ERRORS";
export const RETURN_WARNINGS = "RETURN_WARNINGS";
export const RETURN_INFO = "RETURN_INFO";
export const RETURN_SUCCESS = "RETURN_SUCCESS";

// Course Connect Page
export const GET_COURSES = "GET_COURSES";
export const GET_SEARCH_BAR_INFO = "GET_SEARCH_BAR_INFO";

// Educator Page
export const GET_EDUCATOR = "GET_EDUCATOR";
export const CREATE_EDUCATOR = "CREATE_EDUCATOR";
export const GET_EDUCATOR_COURSES = "GET_COURSES";
export const CREATE_COURSE = "CREATE_COURSE";
export const GET_ED_DETAILS = "GET_ED_DETAILS";
export const RESET_ED_DETAILS = "RESET_ED_DETAILS";
export const GET_ED_LIST_ITEMS = "GET_ED_LIST_ITEMS";
export const CREATE_ED_ITEM = "CREATE_ED_ITEM";

export const GET_COURSE_DETAILS = "GET_COURSE_DETAILS";
export const GET_COURSE_MODULES = "GET_COURSE_MODULES";
export const CREATE_MODULE = "CREATE_MODULE";
export const GET_MODULE_DETAILS = "GET_MODULE_DETAILS";
export const GET_MODULE_LESSONS = "GET_MODULE_LESSONS";
export const CREATE_LESSON = "CREATE_LESSON";
export const GET_LESSON_DETAILS = "GET_LESSON_DETAILS";

// Student Page
export const CREATE_STUDENT = "CREATE_STUDENT";

// Search Page
export const GET_SEARCH_CATEGORIES = "GET_SEARCH_CATEGORIES";